#!/usr/bin/env python3
"""
Clean up .bin files from the workspace.
Useful for removing compiled binary cache files generated by CPH.
"""

import os
import sys
import argparse
from pathlib import Path


def cleanup_bin_files(root_dir: str, dry_run: bool = False, verbose: bool = False) -> int:
    """
    Recursively find and delete all .bin files in root_dir.
    
    Args:
        root_dir: Root directory to search in
        dry_run: If True, only show what would be deleted without actually deleting
        verbose: If True, print details of every file processed
    
    Returns:
        Number of files deleted (or would be deleted in dry_run mode)
    """
    root_path = Path(root_dir)
    if not root_path.exists():
        print(f"❌ Directory does not exist: {root_dir}")
        return 0
    
    bin_files = list(root_path.rglob("*.bin"))
    
    if not bin_files:
        print(f"✓ No .bin files found in {root_dir}")
        return 0
    
    deleted_count = 0
    
    for bin_file in bin_files:
        try:
            if verbose:
                print(f"{'[DRY RUN] ' if dry_run else ''}Deleting: {bin_file}")
            
            if not dry_run:
                bin_file.unlink()
            
            deleted_count += 1
        except Exception as e:
            print(f"⚠️  Failed to delete {bin_file}: {e}")
    
    # Summary
    mode_str = "[DRY RUN] " if dry_run else ""
    print(f"\n{mode_str}Deleted {deleted_count} .bin file(s)")
    
    return deleted_count


def main():
    parser = argparse.ArgumentParser(
        description="Clean up .bin files from workspace (CPH cache cleanup)"
    )
    parser.add_argument(
        "root_dir",
        nargs="?",
        default=".",
        help="Root directory to search (default: current directory)"
    )
    parser.add_argument(
        "-n", "--dry-run",
        action="store_true",
        help="Show what would be deleted without actually deleting"
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output"
    )
    
    args = parser.parse_args()
    
    count = cleanup_bin_files(args.root_dir, dry_run=args.dry_run, verbose=args.verbose)
    
    return 0 if count >= 0 else 1


if __name__ == "__main__":
    sys.exit(main())
